version: '3.7'
services:
  frontend:
    container_name: int_cont_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '8097:8080'
    volumes:
    - '.:/app'
    - '/app/node_modules'
    hostname: 0.0.0.0
    command: /bin/sh -c "yarn serve"
    environment:
      - CHOKIDAR_USEPOLLING=true